version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/golang/protobuf
    versions:
    - 1.4.3
    - 1.5.1
  - dependency-name: github.com/open-policy-agent/opa
    versions:
    - 0.26.0
    - 0.27.0
    - 0.27.1
  - dependency-name: github.com/onsi/gomega
    versions:
    - 1.10.4
    - 1.10.5
